### ISSUE TITLE
Multi-variation Extents

### ISSUE THREAD

**Issue by GACJ** [cccbr/method_ringing_framework#6]
I have just had a thought regarding the newly adopted framework.

The old CC Decisions used to define that if extents were rung consisting of more than one variation, that the variations either had to have the same base method (e.g. Plain Bob rung with Grandsire, Wallflower and Pinks singles gives three distinct variations), or separate methods and the same call (e.g. St. Simon's, St. Martin's, St. Osmund and Eynesbury spliced, using a Grandsire single, would give four variations).

As far as I can tell, this is no longer the case. So if I ring the St. Simon's family spliced, using three different calls, I could construe this to consist of twelve variations. Whilst I am open to permissiveness, I wonder if this is too ambiguous? I appreciate, with most of the descriptive terms associated with performance descriptions there can be ambiguity depending on how things are construed, so perhaps it doesn't matter!

**Comment by tjbarnes23** [comment]
From Ben Waller:
> I have just had a thought regarding the newly adopted framework.
> 
> The old CC Decisions used to define that if extents were rung consisting of more than one variation, that the variations either had to have the same base method (e.g. Plain Bob rung with Grandsire, Wallflower and Pinks singles gives three distinct variations), or separate methods and the same call (e.g. St. Simon's, St. Martin's, St. Osmund and Eynesbury spliced, using a Grandsire single, would give four variations).
> 
> As far as I can tell, this is no longer the case. So if I ring the St. Simon's family spliced, using three different calls, I could construe this to consist of twelve variations. Whilst I am open to permissiveness, I wonder if this is too ambiguous? I appreciate, with most of the descriptive terms associated with performance descriptions there can be ambiguity depending on how things are construed, so perhaps it doesn't matter!

Draft reply -- pls let me have any comments:

Ben -- that's correct that we haven't kept the restrictions in (D) C.3 of the Decisions, and that permissiveness is the reason for this.

There doesn't seem anything wrong with (say) a 480 spliced multi-extent block comprising Plain Bob, St Simon's Bob, Kennington (Plain Bob with a Reverse Canterbury bob) and St Alban (St Simon's Bob with a Reverse Canterbury bob), but (D) C.3 rules this out.

It appears (D) C.3 was intended to prevent bands from "cheating" by inflating the number of methods / variations they rang in a performance when perhaps they didn't use a variation's call in the composition.  Given there are many different ways of describing the same set of changes, we prefer to leave it to bands to describe their performances as they see best.  If a band claims a high m/v count in ways that aren't warranted, the band risks lowering their reputation among those ringers who follow these things, and that should give a sufficient disincentive.  We think it's better for the Central Council not to be involved in trying to police things like this.

**Comment by GACJ** [comment]
I'm happy with that response. Until 2008, Tony Smith analysed peal reports of Doubles Variations and published an annual list of corrections, usually to reduce the number of m/v reported. There seems to be little value in the exercise.

**Comment by tjbarnes23** [comment]
Ok. Agree Tony's previous analysis doesn't seem to add much value.
What's the best way to reply to Ben (and others who submit enquiries)?  Can a message be sent from methods@cccbr.org.uk so we have them all in one Sent Items folder?  Or shall I send it myself and cc: methods@cccbr.org.uk?

**Comment by GACJ** [comment]
The latter. It will be better when the Office365 migration has been done and we have proper cccbr.org.uk mailboxes.

**Comment by tjbarnes23** [comment]
Ok, done.
