### ISSUE TITLE
Standard Colours for Representing  Bells

### ISSUE THREAD

**Issue by GACJ** [cccbr/method_ringing_framework#7]
Raymond Harwood writes:

Having been elected to represent the Norwich Diocesan Association of Ringers at the London 2019 CCCBR meeting I trying to get up to speed with the work of the CCCBR and in particular the Framework.  One thing that I notice is that it does not mention or cover the colour coding of the methods and it is this issue I would like to comment on.

As we are all familiar with diagrams that illustrate a method with a red line to represent the hunt bell and a blue line representing a working bell, my concern is with colours going beyond these two.  At present I am producing a line of clothing and the like where I have illustrated a grid, either vertically, horizontally or as a polar graph.  The colours I have arbitrarily chosen to represent each bell is based solely on producing something which is visually attractive.   

Before my diagrams become more widely known and possibly accepted as the norm or "standard" colours, should a mention be made in the methods framework to address this issue and set a guideline as to which colours should be adopted to represent each bell?  I would hate to be the one who set the precedent as to which colours were selected without universal agreement.

**Comment by tjbarnes23** [comment]
Draft reply to Raymond Harwood:

Raymond,

Thanks for your message.  As you say, there's a well-established practice of using red lines for hunt bells and blue lines for working bells, and the framework follows this tradition in its diagrams (e.g. see section 4.D.1).  Beyond these two colours, we're not aware of any standards or traditions for additional bells, and ringing apps quite often allow users to select which colours they'd like to use for different lines.  Given this, we don't see any problem with you selecting colours that you think are the most visually appealing.

Good luck with your ringing-themed clothing line.

Regards,
Tim

**Comment by GACJ** [comment]
I'm happy with that answer. Raymond says "this issue" - but it is not clear what issue might arise from non-standardisation. I can't think of one, so see no value at all in establishing a standard.

**Comment by tjbarnes23** [comment]
The following now sent to Raymond:

Dear Raymond,

Thanks for contacting us with your message below.  As you say, there's a well-established practice of using red lines for hunt bells and blue lines for working bells, and the framework follows this tradition in its diagrams (e.g. see section 4.D.1).  Beyond these two colours, we're not aware of any standards or traditions for colouring additional bell lines, and ringing software quite often allows users to select which colours they'd like to use for different lines.  Given this, we don't see any issue with you selecting the colours that you think are the most visually appealing for your purposes.

We hope this helps, and good luck with your ringing-themed clothing line.

Regards
Tim
