### ISSUE TITLE
Questions from Barry Peachey

### ISSUE THREAD

**Issue by tjbarnes23** [cccbr/method_ringing_framework#8]
From Barry Peachey -- sent to H&A workgroup:

I'm afraid that the upcoming changes in the Decisions in a couple of month's time are largely a mystery to me, and indeed to many others. I thought it might be useful to ask some questions of someone upon whose advice we can rely

Are the following statements a correct reflection of the new position? I hesitate to use the word 'Rules'

1) 5040 blows on one bell will be published in the Ringing World and counted in the CC analysis as a Peal?

2) 5040 blows on two bells will be published in the Ringing World and counted in the CC analysis as a Peal?

3) 5040 Singles will be published in the Ringing World and counted in the CC analysis as a Peal provided that each of the six possible rows appears 840 times?

4) Singles and Minimus will become a record-able twin-stage Peal? (I nearly used the word 'legitimate' but understand that under the new scheme there is no such thing)

5) 5040 Doubles rung on 8 bells with three bells covering in any order will be counted as a Peal as above?

6) 5040 Minor rung on the front six of a 12 with six covering bells and other similar constructions will be counted as a Peal as above?

**Comment by tjbarnes23** [comment]
Draft reply to Barry:

Dear Barry,

At the conceptual level, the new framework no longer sets rules on what is and isn't a peal.  Instead a peal is defined as any touch with a length of 5000 or more changes (where touch, length and change are also defined in the framework).  If a peal is rung in a way that differs from established norms (e.g. the peal started in rounds but ended in queens), the framework asks for this to be disclosed in the peal report (and the framework lists the established norms).  The framework doesn't set a minimum stage, so touches rung on 1 to 3 bells fall within the definition of a peal if >= 5000 changes.  There is no limit on the number of cover bells, nor where cover bell(s) may appear in the rows (and the framework defines how truth is determined when ringing with cover bells).

Touches >= 5000 changes rung with Singles and Minimus methods also fall within the definition of a peal.  If rung in the normal way (extents of singles with a cover, and extents of minimus), such a touch wouldn't be true, but would have 'accepted truth' as defined in the framework.  If the touch doesn't have accepted truth, a disclosure for falseness is requested in the peal report.  Similarly, if a 5040 of Singles doesn't have all possible rows appearing 840 times each, a disclosure for falseness is also requested.

Applying the above, the answer to all your 6 questions is yes.  In practice, we expect some 3-bell peals will be rung, but expect 1- or 2-bell performances to be very rare (but there will be some, e.g. https://bb.ringingworld.co.uk/view.php?id=344102 and https://bb.ringingworld.co.uk/view.php?id=1156418).

The framework only gives high level requirements for the CC analysis of performances to be produced, leaving it to the H&A team to decide what ringers will be interested in seeing.  We expect 1 and 2-bell performances to get minimal coverage.  The framework does ask for the analysis to separately categorise performances that didn't follow established norms, so that meaningful comparisons to earlier years can be made.

We hope this helps -- please let us know if we can provide anything further.

**Comment by GACJ** [comment]
Is it worth pointing out that the technical note in 3.J.3 says "Ringing a Block that has an Effective Stage of zero (such as all Rounds or all Queens) is not considered method ringing"? This would have to apply to Stage One, so it must be outwith the Norm.

From the point of view of the CC Analysis, it makes sense to simply analyse all peals, and just record the number (at each stage?) that were reported (or was obvious from the report) as being outwith the Norm.

**Comment by tjbarnes23** [comment]
The following updated version now sent to Barry:

Dear Barry,

Thanks for your note below, which was passed to me to respond to.  A peal is defined in the framework as any touch with a length of 5000 or more changes, where touch, length and change are also defined in the framework.  If a peal is rung in a way that differs from established norms (e.g. the peal started in Rounds but ended in Queens), the framework asks for this to be disclosed in the peal report (and the framework lists the established norms).

The framework doesn't set a minimum stage, so touches rung on 1 to 3 bells fall within the definition of a peal if >= 5000 changes.  However, if no bells change places (which must be the case on 1 bell), the framework notes that this isn't considered method ringing, so such a performance would be outside the norms.

There is no limit on the number of cover bells, and the framework defines how truth is determined when ringing with cover bells.

Touches can be constructed using methods of more than one stage.  So 5000 or more changes rung in Singles and Minimus methods also falls within the definition of a peal.  If this is rung in the normal way (extents of singles with a cover, and extents of minimus), such a touch wouldn't be true, but would have 'accepted truth' as defined in the framework.  If the touch doesn't have accepted truth, a disclosure for falseness is requested in the peal report.  Similarly, if a 5040 of Singles doesn't have all possible rows appearing 840 times each, a disclosure for falseness is also requested.

Applying the above, the answer to all your 6 questions is yes.  In practice, we expect some 3-bell peals will be rung, but expect 1- or 2-bell performances to be very rare (but there will be some, e.g. https://bb.ringingworld.co.uk/view.php?id=344102 and https://bb.ringingworld.co.uk/view.php?id=1156418).

The framework only gives high level requirements for the CC analysis of performances to be produced, leaving it to the H&A workgroup to decide what ringers will be interested in seeing.  We expect 1 and 2-bell performances to get minimal coverage.  The framework asks for the analysis to separately categorise performances that didn't follow established norms.

I hope this helps -- please let me know if we can provide anything further.

Regards
Tim
